services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    environment:
      DATABASE_URL: mysql://user:password@database:3306/kortingen_db?serverVersion=8.0

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kortingen_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "33060:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: tail -f /dev/null

volumes:
  mysql_data:
